export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALLNOTIFICATIONS_AS_READ: 'MARK_ALLNOTIFICATIONS_AS_READ',
    START_NITIFICATION_POST: 'START_NITIFICATION_POST',
    FINISH_NITIFICATION_POST: 'FINISH_NITIFICATION_POST',
    RECIVED_NOTIFICATIONS: 'RECIVED_NOTIFICATIONS',
    START_LOGIN: 'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED'
}